### ISSUE TITLE
Support multiple products for code coverage

### ISSUE THREAD

**Issue by Mazyod** [google/arc-xcode-test-engine#11]
Hello again!

In our project, we actually have a workspace with many different subproject .. Then, we use an aggregate target to run all the tests. It would be great if we could specify `"products"` instead of just `"product"` under code coverage to pull the data from all the available targets.

Thanks!

**Comment by jverkoey** [comment]
I believe this was resolved in #13.

**Comment by jverkoey** [comment]
Ah btw - if you want to chat with the core team responsible for this library we hang out on Discord at https://discord.gg/material-motion. Check out the #tools channel.
