### ISSUE TITLE
Using test engine with Quick testing library gets "Unable to parse line" error

### ISSUE THREAD

**Issue by KevM** [google/arc-xcode-test-engine#3]
It seems that the test engine is looking for results with test methods to start with the word `test`. This is not required by [Quick](https://github.com/Quick/Quick) specs. I created a quick (pun intended) [example repo](https://github.com/KevM/Quick-Arc-Example) with specs that pass in Xcode and at the command line but have weird parse errors.

```
> arc unit
Unable to parse line:
Test Case '-[QuickArcExampleTests.CalculatorSpec calculator__should_add_two_numbers]' passed (0.004 seconds).
Unable to parse line:
Test Case '-[QuickArcExampleTests.CalculatorSpec calculator__should_subtract_two_numbers]' passed (0.000 seconds).
```

**Comment by jverkoey** [comment]
I believe it; the parsing we're doing right now is pretty rudimentary. Is there a better pattern to use?

**Comment by jverkoey** [comment]
This is likely the line causing this problem:

https://github.com/google/arc-xcode-test-engine/blob/develop/parser/XcodeTestResultParser.php#L86
