### ISSUE TITLE
Arc unit catches logs as broken tests

### ISSUE THREAD

**Issue by shepting** [google/arc-xcode-test-engine#9]
If there is a piece of code that prints a log containing `error:` anywhere inside it the `arc unit` output will report that the tests are `BROKEN`.
<img width="977" alt="error log" src="https://cloud.githubusercontent.com/assets/48065/22943252/b450efd4-f2a1-11e6-90fa-b92527a67998.png">

I'd be happy to submit a Pull Request if you could point me to the likely culprit.

I originally just tried to change this check ``` if (strpos($line, 'error:') !== false)``` to ``` if (strpos($line, ': error:') !== false)``` (adding the extra colon and space) but it didn't seem to catch this issue. https://github.com/google/arc-xcode-test-engine/blob/develop/parser/XcodeTestResultParser.php#L66

**Comment by jverkoey** [comment]
Ahh those pesky string lookups. What I'd do to sleuth this is add a `print_r($test_results)` statement at [line 55](https://github.com/google/arc-xcode-test-engine/blob/develop/parser/XcodeTestResultParser.php#L55) and see if there's a better string expression we can search for.

**Comment by shepting** [comment]
Will do.

**Comment by Mazyod** [comment]
Apparently, XCTest is throwing out logs with faulty internet environments .. This issues becomes a real pain in the neck.

**Comment by hossamghareeb** [comment]
@jverkoey I think we can close this
